# Generated by Django 5.2.7 on 2026-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
