# Generated by Django 5.2.7 on 2025-12-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
